### ISSUE TITLE
Once I've eaten all my disk with etherslurp, how do I clean up? [EOM]

### ISSUE THREAD

**Issue by benlaurie** [google/trillian-examples#1]

**Comment by sadysnaat** [comment]
From Makefile
https://github.com/google/trillian-examples/blob/13b7e9ca77991d3565c79574cae1c79c194a13f1/etherslurp/Makefile#L44-L48

Please clean your datadir which is $HOME/rinkeby

If you delete datadir you will have to run `make initgeth` again.

**Comment by Martin2112** [comment]
How about a Docs or Makefile PR to make this easier for people?

**Comment by sadysnaat** [comment]
Raised a PR #21. Please review and let me know if any changes are required.
