### ISSUE TITLE
Add an example showing how to utilize Trillian for Key Compromise Transparency

### ISSUE THREAD

**Issue by rmhrisk** [google/trillian-examples#11]
@robstradling from Comodo has a great idea to bring clarity and consistency to the ecosystem on Key Compromises.

For example, recently a CA reseller compromised 23k keys, there have been discussions on:
- How should that key compromise have been demonstrated to the issuer?
- How to prove to the larger community as a whole that keys were compromised and give other CAs an opportunity to not use those keys?

Building something like this on Trillian would be relatively straightforward and would represent a great way to use Trillian and thus would be a good example.

This bug is an attempt to convince @robstradling to consider building an example of what he has in mind on top of Trillian :)

**Comment by AlCutter** [comment]
@robstradling, let me know if/how we can help.
