### ISSUE TITLE
Signed id/size in database tables

### ISSUE THREAD

**Issue by SeanBurford** [google/trillian-examples#1229]
Google's Argon and Xenon logs contain around 2.3B records.  A signed integer can handle the range +/-2.1B.

When cloning Argon I get this message:
```
E0921 06:55:56.360252  685659 database.go:135] tx.Exec(): Error 1264 (22003): Out of range value for column 'id' at row 1
E0921 06:55:56.360316  685659 database.go:135] tx.Exec(): Error 1264 (22003): Out of range value for column 'id' at row 1
E0921 06:55:56.360383  685659 database.go:135] tx.Exec(): Error 1264 (22003): Out of range value for column 'id' at row 1
...
```

By inspection it looks like all that is needed is to alter the leaves and checkpoints tables to use integer unsigned for `id` and `size` respectively.  The code all seems to use `uint64` so once the database has an unsigned int we should be ok up to 4.2B entries.  I'm backing up my database before altering the table, so have not tested that change yet.

Here is where the keys are defined as signed:
https://github.com/google/trillian-examples/blob/master/clone/logdb/database.go#L59-L62

**Comment by mhutchinson** [comment]
Good spot. Yeah, these keys should be unsigned BIGINT.
