### ISSUE TITLE
Missing packages

### ISSUE THREAD

**Issue by paulmattei** [google/trillian-examples#15]
Hi

Running `make trillian` results in lots of missing packages. Am I missing something or am I to go package by package and install the missing dependencies?

Thanks!

:~/go/src/github.com/google/trillian-examples/etherslurp$ make trillian
go get -u github.com/google/trillian
cd /home/paulmattei/go/src/github.com/google/trillian && \
go build ./server/trillian_log_server && \
go build ./server/trillian_log_signer && \
go build ./server/trillian_map_server
cmd/flags.go:23:2: cannot find package "bitbucket.org/creachadair/shell" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/bitbucket.org/creachadair/shell (vendor tree)
	/usr/local/go/src/bitbucket.org/creachadair/shell (from $GOROOT)
	/home/paulmattei/go/src/bitbucket.org/creachadair/shell (from $GOPATH)
server/cloudspanner_storage_provider.go:27:2: cannot find package "cloud.google.com/go/spanner" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/cloud.google.com/go/spanner (vendor tree)
	/usr/local/go/src/cloud.google.com/go/spanner (from $GOROOT)
	/home/paulmattei/go/src/cloud.google.com/go/spanner (from $GOPATH)
merkle/objhasher/objhasher.go:22:2: cannot find package "github.com/benlaurie/objecthash/go/objecthash" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/benlaurie/objecthash/go/objecthash (vendor tree)
	/usr/local/go/src/github.com/benlaurie/objecthash/go/objecthash (from $GOROOT)
	/home/paulmattei/go/src/github.com/benlaurie/objecthash/go/objecthash (from $GOPATH)
server/mysql_storage_provider.go:28:2: cannot find package "github.com/go-sql-driver/mysql" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/go-sql-driver/mysql (vendor tree)
	/usr/local/go/src/github.com/go-sql-driver/mysql (from $GOROOT)
	/home/paulmattei/go/src/github.com/go-sql-driver/mysql (from $GOPATH)
server/trillian_log_server/main.go:23:2: cannot find package "github.com/golang/glog" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/golang/glog (vendor tree)
	/usr/local/go/src/github.com/golang/glog (from $GOROOT)
	/home/paulmattei/go/src/github.com/golang/glog (from $GOPATH)
quota/mock_quota.go:9:2: cannot find package "github.com/golang/mock/gomock" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/golang/mock/gomock (vendor tree)
	/usr/local/go/src/github.com/golang/mock/gomock (from $GOROOT)
	/home/paulmattei/go/src/github.com/golang/mock/gomock (from $GOPATH)
storage/memory/log_storage.go:26:2: cannot find package "github.com/google/btree" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/google/btree (vendor tree)
	/usr/local/go/src/github.com/google/btree (from $GOROOT)
	/home/paulmattei/go/src/github.com/google/btree (from $GOPATH)
types/logroot.go:23:2: cannot find package "github.com/google/certificate-transparency-go/tls" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/google/certificate-transparency-go/tls (vendor tree)
	/usr/local/go/src/github.com/google/certificate-transparency-go/tls (from $GOROOT)
	/home/paulmattei/go/src/github.com/google/certificate-transparency-go/tls (from $GOPATH)
monitoring/prometheus/metrics.go:25:2: cannot find package "github.com/prometheus/client_golang/prometheus" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/prometheus/client_golang/prometheus (vendor tree)
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus (from $GOROOT)
	/home/paulmattei/go/src/github.com/prometheus/client_golang/prometheus (from $GOPATH)
server/main.go:31:2: cannot find package "github.com/prometheus/client_golang/prometheus/promhttp" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/prometheus/client_golang/prometheus/promhttp (vendor tree)
	/usr/local/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOROOT)
	/home/paulmattei/go/src/github.com/prometheus/client_golang/prometheus/promhttp (from $GOPATH)
monitoring/prometheus/metrics.go:26:2: cannot find package "github.com/prometheus/client_model/go" in any of:
	/home/paulmattei/go/src/github.com/google/trillian/vendor/github.com/prometheus/client_model/go (vendor tree)
	/usr/local/go/src/github.com/prometheus/client_model/go (from $GOROOT)
	/home/paulmattei/go/src/github.com/prometheus/client_model/go (from $GOPATH)
Makefile:6: recipe for target 'trillian' failed
make: *** [trillian] Error 1

**Comment by Martin2112** [comment]
Try: `go get -d github.com/google/trillian` before the build.
