### ISSUE TITLE
Typo in the Firmware Transparency Demo Doc

### ISSUE THREAD

**Issue by Ruide** [google/trillian-examples#222]
Doc location: https://github.com/google/trillian-examples/tree/master/binary_transparency/firmware

This line:
``` go run ./cmd/flash_tool/ --logtostderr --update_file=/tmp/update.ota --device_storage=/tmp/dummy_device  # --force if it's the first time```

miss the specification of the device. It shows the following error message.
```F1217 18:17:28.270611   36381 flash_tool.go:53] device must be one of: 'dummy', 'armory'```

We might want to add it as following. Or we might want to change the https://github.com/google/trillian-examples/blob/master/binary_transparency/firmware/cmd/flash_tool/flash_tool.go to have a default dummy device.

might want to change to:
```go run ./cmd/flash_tool/ --logtostderr --update_file=/tmp/update.ota --device_storage=/tmp/dummy_device --device=dummy # --force if it's the first time```

**Comment by AlCutter** [comment]
Ah, good spot - thanks Ruide!
Would you like to send a PR to update the README to add the flag?

**Comment by Ruide** [comment]
> Ah, good spot - thanks Ruide!
> Would you like to send a PR to update the README to add the flag?

Sure, that would be my pleasure!  See https://github.com/google/trillian-examples/pull/223
