### ISSUE TITLE
Provide simple example

### ISSUE THREAD

**Issue by lukehinds** [google/trillian-examples#82]
The current examples are really good, but I think it would be useful to have a 'hello world' level example for those new to trillian. 

Such as start a log server, signer, make a simple entry, retrieve the entry.

**Comment by smeiklej** [comment]
i've just merged a new example (#173) that is hopefully doing exactly this - please check it out and let me know what you think!

**Comment by lukehinds** [comment]
thanks @smeiklej , will take a look

**Comment by mhutchinson** [comment]
Luke I'm going to close this. Please reopen this bug (or better yet, raise a new one) with any specific comments on the new example.
